Add experimental `{auth/login}-callback` auth modes
elan-ev/tobira pull request #1032
Opened 2023-12-14 12:58 UTC by LukasKalbertodt

This PR introduces two new auth modes: `auth-callback` and `login-callback`. The basic idea is that you can configure a `callback_url` in Tobira (e.g. `http://localhost:1234/tobira-auth`) that Tobira contacts at appropriate times to get user information. The system administrator would then setup a service with an HTTP endpoint as described below.

## Comparison to `*-proxy` modes

The new modes are somewhat similar to `full-auth-proxy` and `login-proxy`: `login-callback` will only contact the callback_url on every login attempt and then Tobira's internal session management is used; `auth-callback` contacts the callback_url for every incoming request that needs to be authenticated. The difference between `-proxy` and `-callback` is shown here:

```
*-proxy modes:
                                                                Request with
┌──────┐                ┌─────────┐                ┌────────┐   auth headers   ┌────────┐
│ User │ -------------> │ reverse │ -------------> │ custom │ ---------------> │ Tobira │
│      │                │  proxy  │                │  auth  │                  │        │
│      │                │         │                │  logic │                  │        │
└──────┘                └─────────┘                └────────┘                  └────────┘

*-callback modes:
                                                                            
┌──────┐                ┌─────────┐                ┌────────┐                  ┌────────┐
│ User │ -------------> │ reverse │ -------------> │ Tobira │ ---------------> │ custom │
│      │                │  proxy  │                │        │                  │  auth  │
│      │                │         │                │        │ <--------------- │  logic │
└──────┘                └─────────┘                └────────┘    user info     └────────┘
```

But why these new modes? It adds more complexity to the Tobira code and the Tobira documentation, making it even more confusing to setup Tobira? While in theory, `-proxy` should be fine, `-callback` has a few **advantages**:
- Passing user information via *auth-headers* (`x-tobira-username`, ...) is problematic due to HTTP header size limits. While there are none according to spec, most systems limit the size of all headers. This is problematic when a user has lots of roles, for example one for every course they are in.
- Encoding the auth headers as base64 (while I still stand by the decision) proved very annoying as `nginx` has no built-in easy base64 encoding function, for example. That means that the "custom auth logic" often can't be implemented just in the webserver config.
- Certain logic/features can be coded in Tobira once without every installation having to do it themselves:
  - Only doing authentication on requests that matter: static assets like JS or fonts do not require any auth and should thus not waste resources looking up user information. You can configure it in your nginx, but (a) everyone has to do that -> annoying and duplicate code. And (b) Tobira knows a lot better which requests require auth, i.e. can be more fine-grained about it.
  - Caching for user data. To avoid doing expensive operations to resolve the user info on every request, Tobira can add a short lived cache. That should help a lot with performance and otherwise every admin has to configure/code this themselves.

In fact, we might want to eventually remove the `-proxy` modes in favor of these new callback ones. Of course we don't want to break any existing installation (no panic!). It's just a far future plan in case these callback modes turn out nice and can do everything the `-proxy` modes can do.

## How the new modes work exactly

You have to set `auth.mode` to one of the new modes and also set `auth.callback_url`. The latter can also contain a path. When and how your callback is called depends on the mode:

- **`auth-callback`**: For every request that Tobira receives and that requires authentication, Tobira will contact your callback. That is: a `GET` request with empty body, and where all headers are simply copied from the request Tobira received. 
- **`login-callback`**: On every login attempt (on Tobira's own login page), Tobira sends a request to your callback. That request does not contain any interesting headers, but contains the login data in the body as UTF-8 encoded JSON like this: `{ "userid": "joachim", "password": "blub" }`.

In both modes, your callback is always expected to return UTF-8 encoded JSON. The JSON always has an `outcome` field, plus potentially additional fields. There are two things your callback can return:

- `{ "outcome": "no-user" }`: means that the incoming request is not authenticated (`auth-callback`) or that the login data is invalid somehow (`login-callback`). 
- `{ "outcome": "user", ... }`: means that the incoming request is authenticated (`auth-callback`) or that the login data is valid (`login-callback`). The `...` (the additional fields) specify the user data (the meaning of those fields are equivalent to the auth headers):
  - `username`
  - `displayName`
  - `email` (optional)
  - `roles`

So an example `"outcome": "user"` response might look like:

```json
{
  "outcome": "user",
  "username": "peter",
  "displayName": "Peter Lustig",
  "email": "peter@lustig.de",
  "roles": [
    "ROLE_ANONYMOUS",
    "ROLE_USER",
    "ROLE_COURSE_123",
    "ROLE_COURSE_125"
  ]
}
```

## Example callback services

These just serve as a starting point/example. They are written in TypeScript using [Deno](https://deno.com/) as runtime, but it should be pretty clear what they do. And admins can of course use whatever language they want.

### `auth-callback`

The idea here is that in front of Tobira there is an nginx, which performs a Shibboleth auth-sub-request and adds a number of headers with Shibboleth data to the request. So: Tobira will receive a request with a bunch of `x-shib-*` headers. Of course Tobira doesn't know what to do with those. Those headers will be forwarded by Tobira to the callback which then interprets those. If there is no Shibboleth user, these headers are just missing. (*Note* again that this is just an example and I didn't test this with a real shibboleth at all.)

```ts
const handler = (request: Request): Response => {
  const username = request.headers.get("x-shib-username");
  const displayName = request.headers.get("x-shib-full-name");
  const email = request.headers.get("x-shib-email");

  if (username && displayName) {
    const roles = [
      "ROLE_ANONYMOUS",
      "ROLE_USER",
      ...request.headers.get("x-shib-affiliation") == "staff" ? ["ROLE_STAFF"] : [],
      ...(courseDB[username] ?? []).map(courseId => `ROLE_COURSE_${courseId}`),
    ];

    return Response.json({
      outcome: "user",
      username,
      displayName,
      email,
      roles,
    });
  } else {
    return Response.json({
      outcome: "no-user",
      foo: "Jürß"
    });
  }
};

const courseDB = {
  "peter": [123, 125],
  "sabine": [99, 27, 123],
};

Deno.serve({ port: 1234 }, handler);
```

### `login-callback`

```ts
const handler = async (request: Request): Promise<Response> => {
  const body = await request.json();
  if (body.userid in userDB && userDB[body.userid].password == body.password) {
    const user = userDB[body.userid];
    return Response.json({
      outcome: "user",
      username: body.userid,
      displayName: user.displayName,
      email: user.email,
      roles: user.roles,
    });
  } else {
    return Response.json({
      outcome: "no-user",
    });
  }
};

const userDB = {
  "peter": {
    password: "Haußmeister",
    displayName: "Peter Lustig",
    roles: ["ROLE_ANONYMOUS", "ROLE_USER", "ROLE_STUDENT"],
  },
  "sabine": {
    password: "CatbusGoesBrrr",
    displayName: "Sabine Rudolfs",
    email: "sabine@example.com",
    roles: ["ROLE_ANONYMOUS", "ROLE_USER", "ROLE_STAFF", "ROLE_LECTURER"],
  },
};

Deno.serve({ port: 1234 }, handler);
```

---

## Still TODO:
- [ ] Te [...]

2024-02-07 08:39 UTC, geichelberger commented
The caching of the callback results per node needs to be revised with a distributed setup. This can have funny side effects if the cached data is inconsistent.

2024-02-07 08:47 UTC, LukasKalbertodt commented
Fair point. However, I would note that usually, your load balancer would always forward the same user (as identified by IP address or whatever) to the same node. And more importantly: with this kind of caching, that can hold stale data, there can always be "funny" side effects. 

Making this caching shared between all Tobira nodes basically defeats the purpose, i.e. performance, if the cache. It also adds more complexity. If this caching is not acceptable in your situation, it should be disabled in Tobira. And you can instead have your own cache in the auth callback, for example. All I'm saying is: I had this in mind when deciding for an in-memory/in-process cache.

Thanks for taking a look at this PR!

2024-02-07 08:48 UTC, LukasKalbertodt commented
But I suppose adding a note to the docs about this is a good idea :thinking:

2024-02-07 09:50 UTC, geichelberger commented
Sticky sessions should be avoided if possible; they have some drawbacks.

If both nodes have the same stale data, that's not so problematic, but if one node allows you to edit pages and the other doesn't, it results in weird behavior with a bad user experience.

2024-02-07 09:55 UTC, LukasKalbertodt commented
> Sticky sessions should be avoided if possible; they have some drawbacks.

Ah, I didn't know.

> If both nodes have the same stale data, that's not so problematic, but if one node allows you to edit pages and the other doesn't, it results in weird behavior with a bad user experience.

Certainly. So as I said, then I would disable the Tobira cache to avoid these problems. I don't think it's a good idea to adjust the Tobira cache to be shared between nodes, as it adds complexity and defeats the purpose of the cache as it's likely not much faster than just calling the callback. If you use a multi-node setup and your callback performs expensive operations, then the callback should cache those operations itself.

2024-02-09 15:44 UTC, wsmirnow commented on docs/docs/setup/auth/user/tobira-session.md
> +from_login_credentials = "login-callback:http://localhost:7007"
should this key not appear under `auth.session` section?

2024-02-12 15:56 UTC, JulianKniephoff requested changes
Haven't looked at the code, yet, but went through the docs rather thoroughly. Overall they are very nice docs. I still added quite a few more or less nitpicky comments. Specifically the "writing advice" ones are probably debatable. I stand by them, but none of them need to block this PR, I guess. 🤷‍♀️

2024-02-12 15:56 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/callback.md
> +If you include `"cookie"` in the `relevant_headers` field, all cookies are always forwarded (note: this would usually make the caching fairly useless, so you probably want to disable it then).
Maybe link to the caching section here so I don't have to wonder whether I overread something.

2024-02-12 15:56 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/callback.md
> +By default, Tobira caches responses from the auth callback in-memory, to speed up successive requests from the same user.
```suggestion
By default, Tobira caches responses from the auth callback in memory, to speed up successive requests from the same user.
```

2024-02-12 15:56 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/callback.md
> +The callback can read those headers, and building the user information Tobira expects.
```suggestion
The callback can read those headers, and build the user information Tobira expects.
```

2024-02-12 15:56 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/callback.md
> +Your callback can of course also request additional information from external services, e.g. a list of courses the user is signed up for.
```suggestion
It can of course also request additional information from external services, e.g. a list of courses the user is signed up for.
```

2024-02-12 15:56 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/callback.md
> +  if (!uniqueID || !surname || !givenName || !email) {
```suggestion
  if (!uniqueID || !fullName || !email) {
```

2024-02-12 15:56 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/callback.md
> +Finally, you should configure your nginx in a way that "shibauthorizer" is not ran for routes that don't need authentication.
```suggestion
Finally, you should configure your nginx in a way that "shibauthorizer" is not run for routes that don't need authentication.
```

2024-02-12 15:56 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/trust-auth-headers.md
> +```
See the appropriate comment on the callback doc

2024-02-12 15:56 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/callback.md
> +---
I commented on this in another doc, but it happened multiple times here, too, so I'm not sure it's intended, and will just add a global note like this.

Should 

> shibauthorizer

be

> `shibautorizer`

?

2024-02-12 15:56 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/trust-auth-headers.md
> +All these header values have to be a **base64-encoded UTF-8** string!
```suggestion
All these header values have to be **base64-encoded UTF-8** strings!
```

or

```suggestion
Every one of these header values has to be **base64-encoded UTF-8** string!

2024-02-12 15:56 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/trust-auth-headers.md
>  Alternatively, you can use your own login page of course.
Maybe cross-link to the relevant section about intercepting those?

2024-02-12 17:41 UTC, LukasKalbertodt commented on docs/docs/setup/auth/user/index.md
> +- When using `source = "tobira-session"`, you can set `auth.session.from_login_credentials` to `"opencast"` or `"login-callback:..."`.
Hu? That's not the mode though. Thats `from_login_credentials`. Thats not outdated

2024-02-12 17:43 UTC, LukasKalbertodt commented on docs/docs/setup/auth/user/tobira-session.md
> +You also have to specify an HTTP endpoint and your callback is also expected to return the JSON as specified in the above link.
Mh I don't expect people to read these docs linearly. But instead jump around a ton. And the information is still linked so it's fine I'd say

2024-02-12 17:47 UTC, LukasKalbertodt commented on docs/docs/setup/auth/user/tobira-session.md
> +- [**`"trust-auth-headers"`**](./trust-auth-headers)
I think it's fine, I didn't add a description bc I couldn't think of anything that added any value.

2024-02-12 17:52 UTC, LukasKalbertodt commented on docs/docs/setup/auth/user/tobira-session.md
> +```
It can, but this diagram is old and I don't think it's worth our time to translate it.

2024-02-14 13:38 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/index.md
> +- When using `source = "tobira-session"`, you can set `auth.session.from_login_credentials` to `"opencast"` or `"login-callback:..."`.
I'm just saying: When I set `from_login_credentials = "opencast"` I don't need any of this info, right?

2024-02-15 14:57 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/tobira-session.md
> +You also have to specify an HTTP endpoint and your callback is also expected to return the JSON as specified in the above link.
fair enough, I guess 🤷‍♀️

2024-02-15 14:58 UTC, JulianKniephoff commented on docs/docs/setup/auth/user/tobira-session.md
> +- [**`"trust-auth-headers"`**](./trust-auth-headers)
aight 🤷‍♀️

2024-02-22 09:12 UTC, LukasKalbertodt commented
So, then I think this is good to merge! Multiple people had a look at this and this is deployed on an ETH test system for a while now, working as expected.

2024-02-22 09:13 UTC, merged