Add mechanism for database migration
elan-ev/tobira pull request #108
Opened 2020-12-04 15:28 UTC by LukasKalbertodt

(based on #97, therefore draft)

Closes #77 

See commit messages. 

**TODO** (tho maybe not in this PR?):
- [ ] Add `tobira db migrate [--up-to <index>]` subcommand to manually run the migrations
- [ ]  Think whether running migrations scripts on startup automatically is really a good idea. Then we really have to make sure that the scripts never destroy data in the DB. It is convenient tho.
- [ ] What about multiple tobira nodes? What if all of them start migrating at the same time? Does something break? How to basically globally lock the full DB when running migations?
- [ ] Add mechanism to have checks that can make sure certain things in the DB are correct.

2020-12-07 10:36 UTC, LukasKalbertodt commented
This would be ready to merge now. I think it's fine if we don't include any of the optional tasks in the top comment in this PR. The open questions one should still think about before merging or create dedicated issues for.

2020-12-07 11:03 UTC, JulianKniephoff commented
> What about multiple tobira nodes? What if all of them start migrating at the same time? Does something break? How to basically globally lock the full DB when running migations?

Just wrap the whole thing in a transaction? :thinking:

2020-12-07 11:08 UTC, LukasKalbertodt commented
> > What about multiple tobira nodes? What if all of them start migrating at the same time? Does something break? How to basically globally lock the full DB when running migations?
> 
> Just wrap the whole thing in a transaction?

Does this work? Only if we check within the transaction whether the table already exists, right? Otherwise this might happen, right?

1. Node A checks (in Rust) whether `__db_migrations` exists. -> No
2. Node B checks (in Rust) whether `__db_migrations` exists. -> No
3. Node A & B prepare a long transaction with all migrations.
4. Node B is done and commits the transaction.
5. Node A is done and commits the transaction, but this will now run everything twice, because it is not re-checked whether the `__db_migrations` table exists, right?

2020-12-07 14:55 UTC, JulianKniephoff commented
For the record: As we just discussed, with the right isolation level you are guaranteed that 1. and 2. never happen simultaneously while both of the transactions succeed.

2020-12-07 15:04 UTC, JulianKniephoff requested changes
Very cool! Some minor things, again, and just so that it is also mentioned "officially" in the review again: I would just wrap the whole migration process in one big transaction, using the correct isolation level. And that can probably easily be added as part of this PR, right?

We can then also think about how to handle errors. If the migration fails because of conflicts on concurrent transactions, we might have some kind of retry loop. Or at least inform the user about the fact that they will probably be fine if they just run it again. But this doesn't have to be in this PR, IMO.

2020-12-07 15:23 UTC, LukasKalbertodt commented on backend/server/src/db/query.rs
> +        .map_ok(|row| row.get::<_, String>("table_name"));
Yeah good point. I mean, it's way less important for this code that doesn't run often. But yeah.

2020-12-07 16:25 UTC, LukasKalbertodt commented
I think I fixed everything. Regarding the transaction: my brain does not yet fully accept that this works as expected but yeah, I guess you are right. We use a single serializable transaction now. And I also hope I correctly built the retry-loop. 

I have **not** tested this yet with two actual nodes! Testing this is a bit involved and annoying. I created #109 so that we don't forget that.

2020-12-08 06:33 UTC, JulianKniephoff requested changes
Ok cool, this looks all good now, I think. Except for one little thing: `scripts/schema.sql` can probably be deleted now, right?

2020-12-08 08:34 UTC, JulianKniephoff approved these changes

2020-12-08 08:34 UTC, merged