Enables i18ned footer links
elan-ev/tobira pull request #1119
Opened 2024-02-22 14:27 UTC by geichelberger

This changes the footer custom link type from `string` to `TranslatedString`, enabling links to resources, especially documents like PDFs, in different languages with just one link.

2024-02-23 10:14 UTC, LukasKalbertodt reviewed
That feature makes sense to me! I would still assume that many of those footer entries will only have one link for all languages. And this is a breaking change (which is fine, but slightly annoying to update). Could you make Tobira accept both in the config, a translated map or a simple string? I think it should work with sth like:

```rs
#[derive(Deserialize)]
#[serde(untagged)]
enum OptionallyTranslatedString {
    Translated(TranslatedString),
    Simple(String)
}
```

But I'm not 100% sure. If you can't get it to work quickly, just ping me then either I can try or we can just merge this as is.

2024-02-23 15:54 UTC, geichelberger commented
Initially, I tried to alter the deserialization with Serde to automatically translate a string to a map with an `en` entry as a fallback. So, I added a Visitor to the Deserializer, but it didn't compile.

2024-02-26 10:28 UTC, LukasKalbertodt requested changes
Just a small doc remark, otherwise this is good to go!

2024-02-26 10:28 UTC, LukasKalbertodt commented on backend/src/config/general.rs
> +    ///     { label = { en = "Example" }, link = { en = "https://example.com/en" } },
Can you add another link in this example that does not use translated link? And please add one sentence above this example saying "The link can either be the same for all languages or specified per language." or something like that.

2024-02-26 10:46 UTC, LukasKalbertodt approved these changes

2024-02-26 10:49 UTC, merged