Embedding videos using Opencast IDs
elan-ev/tobira pull request #1174
Opened 2024-06-03 12:08 UTC by geichelberger

Previously, embedding videos was only possible using the Tobira ID. This change introduces the ability to embed videos with Opencast IDs using the same embedding format (`/~embed/!v/:<opencast-id>`). This enhancement improves flexibility and consistency in video embedding options.

2024-06-03 12:39 UTC, LukasKalbertodt requested changes
That feature makes sense to us! 

Looking at the code: could you try to avoid the duplication of code in the GraphQL queries? You can use a fragment for that. Check `routes/Video.tsx` and its `eventFragment` for orientation. I think it should be straight forward? But if you encounter weird problems, feel free to reach out.

2024-06-03 13:28 UTC, geichelberger commented
I did not think about the fragment feature; I introduced a fragment and rebased the PR onto the current master.

2024-06-03 20:50 UTC, LukasKalbertodt requested changes
Just a few comments, otherwise good to go

2024-06-03 20:50 UTC, LukasKalbertodt commented on frontend/src/routes/Embed.tsx
> +            `;
```suggestion
        const query = graphql`
            query EmbedQuery($id: ID!) {
                event: eventById(id: $id) { ... EmbedEventData }
            }
        `;
```

2024-06-03 20:50 UTC, LukasKalbertodt commented on frontend/src/routes/Embed.tsx
> +/** Direct link to video with Opencast ID: `/!v/:<ocid>` */
Copy paste error: just removing this comment is fine.

```suggestion
```

2024-06-03 20:50 UTC, LukasKalbertodt commented on frontend/src/routes/Embed.tsx
> +            </ErrorBoundary>,
The whole JSX expression is exactly the same for both routes. Can you extract that somehow (e.g. a component) to reduce the duplication here?

2024-06-04 07:12 UTC, geichelberger commented on frontend/src/routes/Embed.tsx
> +        fragmentRef.event as EmbedEventData$key,
Now it works with `useFragment<EmbedEventData$key>`. I tried that before, but it was throwing an error. Nevermind it's working now :smile:

2024-06-05 10:10 UTC, LukasKalbertodt approved these changes
Thanks!

2024-06-05 10:10 UTC, merged