Add config to lock video ACLs to their series
elan-ev/tobira pull request #1305
Opened 2024-12-16 11:25 UTC by owi92

This will disable ACL editing for the uploader and the ACL UI when the video is part of a series.
Uploaded videos will then adopt the ACL of that series.

This needs to be configured with `lock_acl_to_series`, the default for this is `false`.

Closes https://github.com/elan-ev/tobira/issues/1006

2025-01-15 10:50 UTC, LukasKalbertodt requested changes
I tested it and it works very well, no problems found there! 

I found a few minor code things, but unfortunately also a bigger one (due to a n+1 query problem). That will require a bit of frontend change as well, but shouldn't be too terrible.

2025-01-15 10:50 UTC, LukasKalbertodt commented on frontend/src/routes/Upload.tsx
> +                    ...lockedAcl.size > 0 && { opacity: .7 },
I think it would be nicer if we wouldn't use an empty map as sentinel value, but rather make the `lockedAcl` a `Map | null` or sth like that. Of course, with one of my prior comments about loading the acl of the series only when it is selected, this might change even more (maybe `Map | "loading" | ...` or sth like that)

2025-01-15 10:50 UTC, LukasKalbertodt commented on frontend/src/routes/Upload.tsx
> +        if (!CONFIG.lockAclToSeries || !metadata.series?.acl) {
Here you also check whether the series even has ACL, but above you don't. I guess this condition should exactly match the one deciding whether the ACL UI is locked.

2025-01-15 10:50 UTC, LukasKalbertodt commented on frontend/src/routes/manage/Video/Access.tsx
> +    const aclLockedToSeries = CONFIG.lockAclToSeries && event.series;
Again: do we also want to check whether the series even has ACL? And unlock it if it hasn't? :thinking:

2025-01-15 12:53 UTC, LukasKalbertodt commented on frontend/src/routes/manage/Video/Access.tsx
> +    const aclLockedToSeries = CONFIG.lockAclToSeries && event.series;
Yep, that makes sense to me! Then I guess just removing this one check from the uploader

2025-01-16 17:14 UTC, LukasKalbertodt requested changes

2025-01-16 17:14 UTC, LukasKalbertodt commented on frontend/src/routes/Upload.tsx
> +            resetField("acl");
Do we really want to reset it in this situation? I would be fine if the ACL that were previously configured would re-eappear when the series is cleared. Not sure whats more useful...

Edit: oh especially when `CONFIG.lockAclToSeries` is not set, then this means that my configured ACLs (which I was able to edit with a series selected) get discarded when I clear the series, right?

2025-01-17 11:37 UTC, owi92 commented on frontend/src/routes/Upload.tsx
> +`;
Hm we need the opencast ID anyway for the ingest, so I didn't think it necessary to also pass the id around.

2025-01-17 12:58 UTC, LukasKalbertodt commented on frontend/src/routes/Upload.tsx
> +`;
Ah yeah I guess it doesn't really matter

2025-01-20 11:06 UTC, merged