Direct series link
elan-ev/tobira pull request #397
Opened 2022-04-05 13:12 UTC by JulianKniephoff

Closes #359.

Can be reviewed commit by commit.

Notably missing is any sort of check whether a user "is allowed" to view a given series, because we haven't figured out what that even means. See TODO.

2022-04-05 14:58 UTC, LukasKalbertodt requested changes
Generally looks good, but I left some remarks.

Also: Please add a DB index for Opencast-ID lookups.

2022-04-06 06:32 UTC, JulianKniephoff commented on frontend/src/routes/Video.tsx
> +
For the record: I disagree that having the start of the condition on the same line as a lengthy type signature is equally as readable, and even with the additional indentation, the entire thing is also still comfortably under 80 chars. :shrug: Indentation in itself is not evil.

Anyway, your opinion seemed to be harder than mine, so whatever.

2022-04-06 06:32 UTC, JulianKniephoff commented on frontend/src/routes/Video.tsx
> +                        {...{ event, realm: realm ?? unreachable("root realm doesn't exist"), id }}
I actually shuffled some more things around. See the new commit(s) and let me know what you think. :wink:

2022-04-06 06:45 UTC, JulianKniephoff commented on frontend/src/routes/Series.tsx
> +    const regex = new RegExp("^/!s/:(.+)", "u");
You mean `/!s/:foo/bar/banana`, right? :thinking: I mean yes, probably not important, but I can probably also easily fix it. :shrug:

2022-04-06 07:01 UTC, JulianKniephoff commented on frontend/src/routes/Series.tsx
> +                    <SeriesBlockFromSeries
Probably even if there is a description. :shrug:

2022-04-06 07:15 UTC, LukasKalbertodt approved these changes

2022-04-06 07:15 UTC, merged