Add user realms (a page tree for each user)
elan-ev/tobira pull request #727
Opened 2023-03-01 13:55 UTC by LukasKalbertodt

Fixes #291 (and more :P)

This PR adds "user realms". Every user (that has a configurable role) can create its own page. They can then edit the contents of that page like a moderator can modify any other page. Users can also add sub pages, i.e. they can build their own realm tree. These pages won't be linked anywhere on the main part of the page and won't appear in the search. Instead, they have to be reached via a manually shared link. This makes sure that normal visitors, expecting a website of that university, don't get surprised. Further, each user realm contains a small note (hidden behind an icon) that explains that the content is user generated.

This is a **draft** as there are still some things that need to be done. I created the PR so that we already have a test deployment one can show. Still TODO:
- [ ] Make realm content edit tools work for non-moderators
- [ ] Remove user realms from search (currently they can be found)
- [ ] Decide about and fix rename dialog in settings (for user root realms)
- [ ] Potentially pull out user-realm-independent changes into their own PRs

2023-03-01 16:59 UTC, LukasKalbertodt commented
The admin UI API check fails because it detected changes in the docs of three API endpoints. Luckily none of these changes will break the Admin UI. So this failed CI status can be ignored, as far as I can see it.

2023-03-16 20:15 UTC, owi92 commented on frontend/src/i18n/locales/de.yaml
> +        Sie können sogar Unterseiten anlegen, um ihr Ihr eigenes kleines Videoportal zu erstellen.
```suggestion
        Sie können sogar Unterseiten anlegen, um Ihr eigenes kleines Videoportal zu erstellen.
```

2023-03-16 20:17 UTC, owi92 commented on frontend/src/i18n/locales/de.yaml
> +        Videoportals auftauchen.
```suggestion
        Darüber hinaus wird Ihre Seite jedoch nicht in der Suche oder im Hauptteil dieses
        Videoportals auftauchen.
```

2023-03-16 20:52 UTC, owi92 commented on frontend/src/i18n/locales/de.yaml
> +        Videoportals auftauchen.
Oh I just saw that this is already outdated/fixed.

2023-03-16 21:27 UTC, owi92 requested changes
This works really well. Codewise I only noticed one redundant word in a translation file.

However, when manually testing this, I found that there seems to be an issue with series blocks in user realm pages and subpages.
More specifically, when clicking on a video that is inside a series block, the video page is not found. I suspect this has something to do with the path also containing the username (e.g. https://pr727.tobira.opencast.org/@sabine/v/Cp-jVAr2Uht).

2023-03-17 07:18 UTC, LukasKalbertodt commented
Good catch! Should be all fixed now.

2023-03-17 11:57 UTC, owi92 commented
Nice, it is indeed fixed.

But now creating user realms appears to break the search index or sth. Pretty sure this wasn't the case yesterday.
To reproduce locally, I think you need to reset the db and rebuild search index -> everything works. Then after creating a user realm, try the search. Alternatively I guess you could also reproduce this with a fresh deployment.
Or maybe you can already see what's wrong from the error message:
```
API Error: 
Internal server error: Error with Meili:
Meilisearch invalid_request: invalid_filter:
Was expecting an operation `=`, `!=`, `>=`, `>`, `<=`, `<`, `TO` or `_geoRadius` but instead got nothing.
19:19 listed = true AND . https://docs.meilisearch.com/errors#invalid_filter (at `search`)
```

2023-03-17 12:45 UTC, owi92 commented
Yeah I was just about to update my comment because I also noted that this wasn't related to user realms at all and happend on every other branch as well, exclusively with the admin account as you said :D

2023-03-17 13:00 UTC, owi92 approved these changes

2023-03-17 13:01 UTC, merged