Increase dashboad coherence
elan-ev/tobira pull request #896
Opened 2023-07-03 12:00 UTC by owi92

Following the discussion in #808, this is a proposal as to how a more coherent version of the dashboard and management pages could look.

Things that were adjusted:
- Dashboard item descriptions (I tried to find a compromise between the discussed suggestions)
- "Manage pages?" text was removed (there's still the question if and where that text should be shown instead. @oas777  and @dagraf suggested moving this to the user page instead and I think this makes sense - perhaps we could add this to the info tooltip)
- The navigation for the "dashboard", "my videos" and "upload" pages were removed. This is a little controversial but I do agree with the points from #808 (i.e. it's somewhat confusing to not have every item from the actual dashboard page present, and navigation is redundant as there are breadcrumbs as well as the user menu which basically fill the same function)

Still missing but not forgotton:
- updated icon for the "my page" links.

This all is of course still subject to change, but maybe this PR-deployment can give us a better base for further discussions.

2023-07-04 06:53 UTC, oas777 commented
Thanks, Ole, this is a great improvement. Some remaining smaller issues:

- With the navigation gone, the page is more aligned to the left than others - can we prevent this?
- Three elements in the first line, one in the second line, this still bugs me. Anything we can do?

2023-07-04 08:46 UTC, dagraf commented
Nicely done. I like the new version.

> * With the navigation gone, the page is more aligned to the left than others - can we prevent this?
I would suggest to left align the title and the buttons for every wideness of the browser window. At the moment, the content of the dashboard is centered when the window is wide, and it gets kind of left aligned when the window gets narrower.


> * Three elements in the first line, one in the second line, this still bugs me. Anything we can do?
This depends on the wideness of your browser window. If you make it very wide all elements appear on the same line. Said that, I do not have problems with the elements spread on different line. Also because in the near future there will be additional elements, I guess (i.e., "My series").

2023-07-04 08:48 UTC, dagraf commented
> * "Manage pages?" text was removed (there's still the question if and where that text should be shown instead. @oas777  and @dagraf suggested moving this to the user page instead and I think this makes sense - perhaps we could add this to the info tooltip)

I have no strong opinion here. I would suggest, you develop it as describeed above and we can then give feedback on how it looks and feels. Ok?

2023-07-05 10:24 UTC, owi92 commented
Seeing as both of you have a different opinion about the alignment of the items, I made some screenshots of the suggested versions to compare, assuming I understood them correctly (keep in mind that the layouts are also applied to the "Upload" and "My videos" page, I've added smaller screenshots of these as well, you can click on them to see them in large):

(1) Olaf's suggestion: Having the content aligned as if there was an invisible navigation to the left, and using an even number of items for each row. This makes it look nicely centered and coherent with other pages that use a navigation box on the left, _but_ 
- (a) as David also mentioned: there will be additional items in the future, so we can't guarantee that there will always be an even number of items
- (b) While this works for the "Dashboard" page, it looks rather odd on the "Upload" and "My videos" pages, since their content is considerably wider, making them right-aligned with a large empty space on the left.
<img width="700" alt="Bildschirmfoto 2023-07-05 um 11 32 47" src="https://github.com/elan-ev/tobira/assets/94838646/b21393cd-4c47-4ddc-8933-15aee0a1d5ac">
<img width="310" alt="Bildschirmfoto 2023-07-05 um 12 19 41" src="https://github.com/elan-ev/tobira/assets/94838646/f4c2b7fb-9ff2-461d-bcb3-c2838b0e681d"><img width="310" alt="Bildschirmfoto 2023-07-05 um 12 19 51" src="https://github.com/elan-ev/tobira/assets/94838646/f3df47ea-0d87-4c20-bbf3-6183f6b8e056">

(2) David's suggestion (aligning the content left): This would actually work better than my version for the "Upload" and "My videos" pages, as they would simply fill the available width (up to a certain point at least).
 I don't see any issues here, apart from the one that Olaf also noticed on my suggestion (With the navigation gone, the page is more aligned to the left than others). 
<img width="700" alt="Bildschirmfoto 2023-07-05 um 11 24 34" src="https://github.com/elan-ev/tobira/assets/94838646/8baa0d3f-de77-4373-80fa-3507030ec8cd">
<img width="310" alt="Bildschirmfoto 2023-07-05 um 12 18 58" src="https://github.com/elan-ev/tobira/assets/94838646/ddb63b2e-02a6-4736-ad52-b3e8514ac9e6"><img width="310" alt="Bildschirmfoto 2023-07-05 um 12 19 15" src="https://github.com/elan-ev/tobira/assets/94838646/5129c68d-8272-4982-a877-2a3e883d80fd">

If we have some time left, maybe we can talk about these and agree on one version this afternoon. @LukasKalbertodt your opinion is of course also appreciated and should be taken into account.

2023-07-05 14:40 UTC, oas777 commented
David, we didn't decide this, but there was a discussion about

- whether the left-hand navigation should be "deleted" only in the "Dashboard" or in its sub-pages as well ("My videos" e. g.) and
- the width of the pages in general and in particular ("My videos" and "Upload video").

We'll continue here later...

2023-07-05 15:53 UTC, LukasKalbertodt commented
The problem with "pretending there is an invisible navigation" is that the navigation side bar has a fixed width, while the "main content" can stretch very close to the right screen boundary. Meaning: on some screen widths it might look good as it looks center-aligned, but on others it looks really weird. 

I would also strongly suggest that we shouldn't remove the navigation on at least the sub pages. Switching from "my videos" to "my series" (in the future) or "upload video" is something fairly common I would think. 

---

Given these two points, I'd suggest going in the different direction: always show the navigation but add the entries "my page" and "Record video" to it. I know, I argued against this before, as those are two "different kind of items": 
- "my page" is not technically part of the "managment area" and thus shows a different navigation:
  ![image](https://github.com/elan-ev/tobira/assets/7419664/3385c1d4-4fbc-46f4-ad6d-56c8db756393)
- "Record video" opens Studio in a new tab.

But thinking about it again, I think it's fine. After all, we gain more consistency from that. For the "Record video" entry I would also add the ["external link" icon](https://feathericons.com/?query=external-link) to make it less surprising.

Additionally, I would actually remove basically all of the content from the "main" area of the management dashboard, i.e. remove those four boxes. They are completely redundant, as we would have everything in the navigation. I think we will find some interesting data to fill this content with, but even if it's completely empty it's fine IMO.

Please compare that to the YouTube Studio, Youtube's equivalent of our "management area":

![youtube-dashboard](https://github.com/elan-ev/tobira/assets/7419664/09179abc-78e9-413d-a21f-4c363ff644a3)

This is the start page of their "management area", i.e. the page we are talking about here. They show the main menu to jump between the most important "management sub areas". And on the main part of the start page they show... random stuff. This terrible "creator insider" videos is completely annoying, of course. Other than that they show analytics and latest comments, which is useful. I could imagine something similar for Tobira. Quick links to the three last uploaded videos for example. Maybe some analytics/statistical data in the future, if we have some. I'm sure we can come up with a few things. But until we do, I think a basically completely empty dashboard is fine too. Users will quickly learn that the navigation is the way to get to actually useful pages.

I.e. something like this for now:

![image](https://github.com/elan-ev/tobira/assets/7419664/3b9b38d5-95ec-4415-8a8f-d5a157dc5792)

2023-07-06 07:40 UTC, oas777 commented
- +1 for adding "My page" and "Record video" to the navigation
- +1 for always showing the navigation
- -1 regarding empty main area. Let's revisit this once the above two have been implemented and we have some ideas what to present in this "wasteland".

2023-07-06 15:44 UTC, owi92 commented
I have updated this according to @LukasKalbertodt's suggestion.
A few additional notes:
- While the tiles were removed for now, I have re-added the "Manage pages?" text. Even though I've also said previously that I could imagine moving this to the user page, I reconsidered and came to the conclusion that not every user that needs to "manage pages" will have their own page. The text provides valuable information and having this on the "Manage" page is pretty much the only place where it makes sense, in my opinion.
- The single remaining page that doesn't have a navigation on the left is the page a user gets directed to when they visit "My Page" and don't have their own page yet. I would argue that for the sake of coherence we might also want to add the navigation there.

2023-07-07 11:58 UTC, oas777 commented
- +1 for re-adding this. I wanted to -1 this when I read it, but it actually looks good on that "wasteland". Maybe remove the "?"?
- +1
- What about "adding "My page" and "Record video" to the navigation"? Later?

2023-07-07 12:37 UTC, owi92 commented
> Maybe remove the "?"?

Makes sense, I think the questionmark is not really necessary.

> What about "adding "My page" and "Record video" to the navigation"? Later?

Sorry, I didn't specifically mention this, but I've added these as well. 
For reference, you can check the deployment at https://pr896.tobira.opencast.org/~manage with a signed-in user (I would suggest admin, as not every test-user is allowed to record videos).

2023-07-07 13:08 UTC, oas777 commented
Looks good! David?

2023-07-07 20:51 UTC, dagraf commented
Looks good. But we should come up with more reasonable content to fill the 'wasteland'.

2023-07-11 08:21 UTC, LukasKalbertodt commented
> Looks good. But we should come up with more reasonable content to fill the 'wasteland'.

What do you think about my suggestion of showing the latest videos of that user? I.e. the first 5 videos from the "My Videos" page. Not in the same table as "My Videos", but just showing the title and a small thumbnail (and making them link to the ["manage single video" page](https://pr896.tobira.opencast.org/~manage/videos/LWibjnBm6V5)).

2023-07-11 10:19 UTC, oas777 commented
PS: Or we table the discussion in line with https://github.com/elan-ev/tobira/issues/807 until we have more features to be included. I hear neither "My series" nor "My collections" actually exist, Matomo has not been integrated yet and access cannot be granted either, so nothing I said would be feasible currently.

2023-07-12 08:24 UTC, LukasKalbertodt commented
> PS: Or we table the discussion in line with #807 until we have more features to be included. 

I think this would be useful. So I'm in favor of merging this as is, with only the "edit pages" note in the main area. At least we gain consistency from that. And later we can decide about what to do in the main area.

2023-08-21 10:30 UTC, LukasKalbertodt requested changes
Unfortunately, I noticed two problems with the mobile navigation (burger menu):

- When clicking on "my page" and if the user page has not been created, then the burger menu disappears but still counts as open. That's because there is no navigation on that page. I know we talked about this and decided to not put navigation there, but I think we didn't have any strong arguments and now this burger menu problem is a strong argument for including the manage navigation there. (If the user page already exists, I think it works fine as is)
- The "external link" icon of "record video" does not appear in the burger menu. Gosh, we really need to finally do #840, we ran into this so often now already...

But with these two fixed, this can finally be merged.

2023-08-24 10:59 UTC, owi92 commented
Oh well I just realized that I misunderstood your second comment. The icon did show up in the burger menu but the link wasn't styled correctly, so at first I thought that's what you meant... But I believe you meant the external link in the mobile userbox menu since that's where it is missing the icon.

2023-08-24 15:41 UTC, merged

2023-08-25 06:58 UTC, oas777 commented
Ole, is this visible at https://tobira.opencast.org/~manage already?

2023-08-25 08:20 UTC, owi92 commented
Yes, it is.

2023-08-25 08:42 UTC, oas777 commented
Thanks, Ole. I think I need some time to get used to that emptiness... but I looks calmingly clean.

One minor issue: When coming back to the dashboard tab from Studio, both "Record video" and the last other function I used are highlighted:
![grafik](https://github.com/elan-ev/tobira/assets/1752342/2d8d19c2-dd61-47ab-97e5-18a22ffcb110)
I think only "Record video" should be.

2023-08-25 08:54 UTC, owi92 commented
You are right, thanks for bringing this up.

The page the user is currently on is always highlighted, so when someone is on the "My videos" page for example, and then clicks the "Record video" link, they are technically still on the "My videos" page, so that keeps being highlighted.

I would probably change it so that "Record video" won't be highlighted when that link is clicked.

2023-08-25 11:08 UTC, owi92 commented
Should be fixed with https://pr925.tobira.opencast.org/~manage.