Add configurable known groups
elan-ev/tobira pull request #963
Opened 2023-10-16 13:17 UTC by LukasKalbertodt

Fixes #952

Known groups are stored in the database and manipulated via CLI commands. This makes it a lot easier to script and/or add lots of groups, compared to storing them in the config file. The documentation added in one of the later commits should explain everything in detail, and the commit messages should help understand this patch. Can be reviewed commit by commit.

2023-10-20 14:12 UTC, owi92 requested changes
Good work, the commands for adding/updating/etc. the `known groups` are all working very well.

I noticed two things during my testing:
- `db clear` and `db reset` aren't working unless the `hstore` extension is manually dropped from the db first (`db error: ERROR: cannot drop type ghstore because extension hstore requires it. HINT: You can drop extension hstore instead.`).
- The `superset` detection thing in the access ui isn't using the `implies` field of the `known_groups` table entries yet, so the only groups regarded as supersets are the default ones (everyone, logged in users).

2023-10-20 14:12 UTC, owi92 commented on frontend/src/ui/Access.tsx
> +const buildDag = (knownGroups: KnownRoles): GroupDag => {
This doesn't use the supersets/`implies` entries from `groups.json` yet (there is a `TODO` for that in line 662). Do you plan to do this in a follow up PR?

2023-10-23 13:19 UTC, LukasKalbertodt commented
Well done catching those! It should all be fixed now. The `db reset` thing is a new commit, everything else is amended and should be visible in the force-push-compare-button.

2023-10-23 13:53 UTC, owi92 approved these changes
👌

2023-10-23 13:53 UTC, merged